apiVersion: v1 
kind: Service 
metadata: 
  name: frontend-service
spec: 
  selector: 
    app: frontend-app 
  ports: 
  - name: tomcat 
    targetPort: 30080
    port: 30080
  type: NodePort 
